[package]
name = "baekjoon_recommend"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"

